# Generated by Django 6.1 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=120, unique=True)),
                ('age', models.PositiveIntegerField()),
            ],
            options={'ordering': ('name', 'id')},
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=160, unique=True)),
            ],
            options={'ordering': ('title', 'id')},
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=240)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField()),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='posts',
                        to='blog.author',
                    ),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='posts',
                        to='blog.topic',
                    ),
                ),
            ],
            options={
                'ordering': ('-publication_date', '-id'),
                'indexes': [
                    models.Index(
                        fields=['topic', 'author'],
                        name='post_topic_author_idx',
                    ),
                    models.Index(
                        fields=['author', 'topic'],
                        name='post_author_topic_idx',
                    ),
                    models.Index(
                        fields=['-publication_date', '-id'],
                        name='post_newest_idx',
                    ),
                ],
            },
        ),
    ]
